language: python
python:
- '3.5'
script:
- echo hello
deploy:
- provider: pypi
  distributions: sdist bdist_wheel
  server: https://testpypi.python.org/pypi
  user: glevente
  password: PyPI1234
  on:
    branches:
      only:
        - master
        - /([0-9].[0-9].[0-9])/
    tags: true
