language: python
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
python:
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy3"

install:
  - pip install -r requirements.txt
  - python setup.py -q install
  
# command to run tests
script: make test

matrix:
  fast_finish: true
sudo: false
notifications:
  email: false