language: python
#cache:
#  directories:
#  - "$HOME/.cache/pip"
#  - "$HOME/.pyenv"
python:
  - "3.5"
#  - "nightly"
#  - "pypy3"

#install:
#  - pip install -r requirements.txt
#  - python setup.py -q install

#matrix:
#  fast_finish: true
#sudo: false
#notifications:
#  email: false
script: echo hello

deploy:
#  provider: pypi
#  user: halftome
#  password:
#    secure: zcIHP2xcT7WsDjXQxyqF2M0suh6gJqBHDn5iISBRf9tWlq8yVzNLg3eKP3jRjj79nDl5v/tDLJGuW6c8jMsRe3kNuoVwGTLj4VAu/PTj8qXdWMoyUIvWGEzJh7T4qglLsHe+S7Am8raKVGWMDNuJFzeeJd8zybr0ktnNVNHmP2/HH7et3v4OnBCQZfVJlfkeQKf+tHdVNAGYXyGIxs+LNx2SuEhpIx9GU6tpZP/uafb7dmj1K/Xlc5v6hVnWt+60dO3lW37drxVVOaBzQRO6/U6T136bn68yu6IlKU/3x0AiWJKOrNw1ULOzrUVQxl8Mg9i/lChR+WVHexRSYsZoWHzhMA01pEa6seILFBVyKtg7MYe1tFrSnJyVntct9rzHoDizR/2jwlPXZAsqQ2U9UFw3rS3fo3S3CADRnj4hwdkc+af+3t2NrhlOqgpmIw4XL9CZCKl0Gvk8rwgP8DXp78ATpQsuJbuiqWiwNPWiaj7XupnVZYd8Vsjc59si0XNbQ1G00ggyPgWrOaKsieGlggApXClq+yoshY8LbDRfZ3ZJ+z9Wxu8lNquOdXEfms1dwz1UppyF6OS4YrTtoUlH1jGcaVAE2gB6Cmpfpz9vtnQSsPjtO/xotXLDE4f36zFO0J7FnnfxnwWtjBlsSyjUqME6u2RJb+yWvYAO3bN6E3U=

  #deploy to testpypi
  provider: pypi
  distributions: sdist bdist_wheel
  server: https://testpypi.python.org/pypi
  user: glevente
  password:
    secure: qdvbTdnAt32N58dHHHxND9zhHyMPjTAd3H2TY4KVjrU7tX1QU8vna3lT/fLD8hV199NReCcnTivbZfnh+9DbLrAWDBR5WLr+gZalsdV2W427XFM1XneOXMTGAK5bXBjssIdLSySQJSpecL3ckomOdhzEzrcdwwWY67WFAVcBHAON2Sz7NjYp+cGTLSXnBPiUg36Ygl1JiYMGYlzNtq+Qm8RmF2TjCEtjTMPBmVepzpCROghHO0PO1Y/CtNgkkwRXj3JbClTpJVUvBd/MMvk8S7QXA3OnVAsKnSI/GzUq4c4cLg7FNeKcPHFbEGUyeQ9J4I8ixHyiEQSycm8A4tCyTzcC7gz/bB3M4132Id+b34CD5SF4ORxxgOgh4mdeuxYvFXT9ZfXHMHA5PM1VZAxW6FemTjChpAMEil4qOI2tyUcxYfMzaHG8VBWGBpzzRE9y36Cs2pDBJByEBuYHFtGwBKrH2tNiEHtTMPFIj8Jx+Kt6C5eHagGRrZ2l4kuyDmyxKWw+/G8sl+oY6Zp4L0qt+lFzcVFlN6Yn1jslsRqws3tMMCfYRzVnGeExkHjZ9FtMdfPX1wlffJo9ttt/DXFkk2xGobx9Ja9Ka2S6EDz+6KDrcVrPDfRxiOvZPSeXa0upufs09eHVwVXB6PVymju1uihFCLyZ1QONEZtCtbT3JuQ=
  on:
    tags: true
    branch: pypi #test branch
#    repo: half2me/libant
